// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CredentialsValidator is an autogenerated mock type for the CredentialsValidator type
type CredentialsValidator struct {
	mock.Mock
}

// ValidateCredentials provides a mock function with given fields: login, password
func (_m *CredentialsValidator) ValidateCredentials(login string, password string) error {
	ret := _m.Called(login, password)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCredentials")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(login, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateLogin provides a mock function with given fields: login
func (_m *CredentialsValidator) ValidateLogin(login string) error {
	ret := _m.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for ValidateLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(login)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidatePassword provides a mock function with given fields: password
func (_m *CredentialsValidator) ValidatePassword(password string) error {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCredentialsValidator creates a new instance of CredentialsValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialsValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialsValidator {
	mock := &CredentialsValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
