// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Input is an autogenerated mock type for the Input type
type Input struct {
	mock.Mock
}

// Print provides a mock function with given fields: message
func (_m *Input) Print(message string) {
	_m.Called(message)
}

// Printf provides a mock function with given fields: format, args
func (_m *Input) Printf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Println provides a mock function with given fields: message
func (_m *Input) Println(message string) {
	_m.Called(message)
}

// ReadPassword provides a mock function with no fields
func (_m *Input) ReadPassword() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadPassword")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadString provides a mock function with given fields: delim
func (_m *Input) ReadString(delim byte) (string, error) {
	ret := _m.Called(delim)

	if len(ret) == 0 {
		panic("no return value specified for ReadString")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(byte) (string, error)); ok {
		return rf(delim)
	}
	if rf, ok := ret.Get(0).(func(byte) string); ok {
		r0 = rf(delim)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(byte) error); ok {
		r1 = rf(delim)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewInput creates a new instance of Input. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInput(t interface {
	mock.TestingT
	Cleanup(func())
}) *Input {
	mock := &Input{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
