// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	slog "log/slog"

	mock "github.com/stretchr/testify/mock"
)

// Output is an autogenerated mock type for the Output type
type Output struct {
	mock.Mock
}

// Debug provides a mock function with given fields: message
func (_m *Output) Debug(message string) {
	_m.Called(message)
}

// Debugf provides a mock function with given fields: format, args
func (_m *Output) Debugf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Error provides a mock function with given fields: message
func (_m *Output) Error(message string) {
	_m.Called(message)
}

// Errorf provides a mock function with given fields: format, args
func (_m *Output) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// GetLogger provides a mock function with no fields
func (_m *Output) GetLogger() *slog.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogger")
	}

	var r0 *slog.Logger
	if rf, ok := ret.Get(0).(func() *slog.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slog.Logger)
		}
	}

	return r0
}

// Info provides a mock function with given fields: message
func (_m *Output) Info(message string) {
	_m.Called(message)
}

// Infof provides a mock function with given fields: format, args
func (_m *Output) Infof(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Plain provides a mock function with given fields: message
func (_m *Output) Plain(message string) {
	_m.Called(message)
}

// Plainf provides a mock function with given fields: format, args
func (_m *Output) Plainf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Success provides a mock function with given fields: message
func (_m *Output) Success(message string) {
	_m.Called(message)
}

// Successf provides a mock function with given fields: format, args
func (_m *Output) Successf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Warning provides a mock function with given fields: message
func (_m *Output) Warning(message string) {
	_m.Called(message)
}

// Warningf provides a mock function with given fields: format, args
func (_m *Output) Warningf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// NewOutput creates a new instance of Output. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutput(t interface {
	mock.TestingT
	Cleanup(func())
}) *Output {
	mock := &Output{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
