// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	storage "github.com/Rusich90/GophKeeper/internal/client/storage"
)

// SecretService is an autogenerated mock type for the SecretService type
type SecretService struct {
	mock.Mock
}

// AddSecret provides a mock function with given fields: ctx, storageData, secret
func (_m *SecretService) AddSecret(ctx context.Context, storageData *storage.Storage, secret *storage.Item) error {
	ret := _m.Called(ctx, storageData, secret)

	if len(ret) == 0 {
		panic("no return value specified for AddSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.Storage, *storage.Item) error); ok {
		r0 = rf(ctx, storageData, secret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSecret provides a mock function with given fields: ctx, storageData, secretID
func (_m *SecretService) DeleteSecret(ctx context.Context, storageData *storage.Storage, secretID string) error {
	ret := _m.Called(ctx, storageData, secretID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.Storage, string) error); ok {
		r0 = rf(ctx, storageData, secretID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FilterSecretsByType provides a mock function with given fields: ctx, storageData, secretType
func (_m *SecretService) FilterSecretsByType(ctx context.Context, storageData *storage.Storage, secretType string) ([]storage.Item, error) {
	ret := _m.Called(ctx, storageData, secretType)

	if len(ret) == 0 {
		panic("no return value specified for FilterSecretsByType")
	}

	var r0 []storage.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.Storage, string) ([]storage.Item, error)); ok {
		return rf(ctx, storageData, secretType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *storage.Storage, string) []storage.Item); ok {
		r0 = rf(ctx, storageData, secretType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *storage.Storage, string) error); ok {
		r1 = rf(ctx, storageData, secretType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindSecretByIDPrefix provides a mock function with given fields: ctx, storageData, idPrefix
func (_m *SecretService) FindSecretByIDPrefix(ctx context.Context, storageData *storage.Storage, idPrefix string) (*storage.Item, []storage.Item, error) {
	ret := _m.Called(ctx, storageData, idPrefix)

	if len(ret) == 0 {
		panic("no return value specified for FindSecretByIDPrefix")
	}

	var r0 *storage.Item
	var r1 []storage.Item
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.Storage, string) (*storage.Item, []storage.Item, error)); ok {
		return rf(ctx, storageData, idPrefix)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *storage.Storage, string) *storage.Item); ok {
		r0 = rf(ctx, storageData, idPrefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *storage.Storage, string) []storage.Item); ok {
		r1 = rf(ctx, storageData, idPrefix)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]storage.Item)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *storage.Storage, string) error); ok {
		r2 = rf(ctx, storageData, idPrefix)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateSecret provides a mock function with given fields: ctx, storageData, secret
func (_m *SecretService) UpdateSecret(ctx context.Context, storageData *storage.Storage, secret *storage.Item) error {
	ret := _m.Called(ctx, storageData, secret)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.Storage, *storage.Item) error); ok {
		r0 = rf(ctx, storageData, secret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStorage provides a mock function with given fields: ctx, storageData
func (_m *SecretService) UpdateStorage(ctx context.Context, storageData *storage.Storage) error {
	ret := _m.Called(ctx, storageData)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStorage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.Storage) error); ok {
		r0 = rf(ctx, storageData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSecretService creates a new instance of SecretService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretService {
	mock := &SecretService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
