// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	storage "github.com/Rusich90/GophKeeper/internal/client/storage"
)

// SyncService is an autogenerated mock type for the SyncService type
type SyncService struct {
	mock.Mock
}

// Sync provides a mock function with given fields: ctx, session
func (_m *SyncService) Sync(ctx context.Context, session *storage.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSyncService creates a new instance of SyncService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSyncService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SyncService {
	mock := &SyncService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
