// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	pb "github.com/Rusich90/GophKeeper/pkg/pb"
)

// SyncServer is an autogenerated mock type for the SyncServer type
type SyncServer struct {
	mock.Mock
}

// Pull provides a mock function with given fields: _a0, _a1
func (_m *SyncServer) Pull(_a0 context.Context, _a1 *emptypb.Empty) (*pb.SyncResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 *pb.SyncResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty) (*pb.SyncResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *emptypb.Empty) *pb.SyncResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.SyncResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *emptypb.Empty) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Push provides a mock function with given fields: _a0, _a1
func (_m *SyncServer) Push(_a0 context.Context, _a1 *pb.SyncRequest) (*pb.SyncResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 *pb.SyncResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.SyncRequest) (*pb.SyncResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.SyncRequest) *pb.SyncResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.SyncResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.SyncRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedSyncServer provides a mock function with no fields
func (_m *SyncServer) mustEmbedUnimplementedSyncServer() {
	_m.Called()
}

// NewSyncServer creates a new instance of SyncServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSyncServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *SyncServer {
	mock := &SyncServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
