// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SyncServiceInterface is an autogenerated mock type for the SyncServiceInterface type
type SyncServiceInterface struct {
	mock.Mock
}

// Pull provides a mock function with given fields: ctx, login
func (_m *SyncServiceInterface) Pull(ctx context.Context, login string) ([]byte, int64, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 []byte
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, int64, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int64); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, login)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Push provides a mock function with given fields: ctx, login, encryptedData
func (_m *SyncServiceInterface) Push(ctx context.Context, login string, encryptedData []byte) (int64, error) {
	ret := _m.Called(ctx, login, encryptedData)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (int64, error)); ok {
		return rf(ctx, login, encryptedData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) int64); ok {
		r0 = rf(ctx, login, encryptedData)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, login, encryptedData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSyncServiceInterface creates a new instance of SyncServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSyncServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *SyncServiceInterface {
	mock := &SyncServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
