// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	storage "github.com/Rusich90/GophKeeper/internal/client/storage"
	mock "github.com/stretchr/testify/mock"
)

// TableRenderer is an autogenerated mock type for the TableRenderer type
type TableRenderer struct {
	mock.Mock
}

// RenderCardTable provides a mock function with given fields: items
func (_m *TableRenderer) RenderCardTable(items []storage.Item) {
	_m.Called(items)
}

// RenderDuplicatesTable provides a mock function with given fields: items
func (_m *TableRenderer) RenderDuplicatesTable(items []storage.Item) {
	_m.Called(items)
}

// RenderLoginTable provides a mock function with given fields: items
func (_m *TableRenderer) RenderLoginTable(items []storage.Item) {
	_m.Called(items)
}

// RenderTextTable provides a mock function with given fields: items
func (_m *TableRenderer) RenderTextTable(items []storage.Item) {
	_m.Called(items)
}

// NewTableRenderer creates a new instance of TableRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTableRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TableRenderer {
	mock := &TableRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
