// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeSyncServer is an autogenerated mock type for the UnsafeSyncServer type
type UnsafeSyncServer struct {
	mock.Mock
}

// mustEmbedUnimplementedSyncServer provides a mock function with no fields
func (_m *UnsafeSyncServer) mustEmbedUnimplementedSyncServer() {
	_m.Called()
}

// NewUnsafeSyncServer creates a new instance of UnsafeSyncServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeSyncServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeSyncServer {
	mock := &UnsafeSyncServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
